### ISSUE TITLE
cannot create account 

### ISSUE THREAD

**Issue by bitkarrot** [ArcadeLabsInc/arc#30]
on https://alpha.thearcapp.com/create

I tried to create a new account using the Firefox browser  but it would not let me proceed after i filled out the form and clicked 'create'

in console.log
<img width="696" alt="Screenshot 2023-01-08 at 5 40 48 PM" src="https://user-images.githubusercontent.com/73979971/211229522-c5da6d16-5714-4fd7-8a4a-b8b2a5ad27c4.png">

create login page: 
<img width="456" alt="Screenshot 2023-01-08 at 5 39 09 PM" src="https://user-images.githubusercontent.com/73979971/211229540-b24bb8a3-b352-4468-8862-5f783ed8463a.png">

**Comment by bitkarrot** [comment]
interestingly, when i close the browser and then reopen it to the same url, its actually logged me in!

**Comment by ArcadeCityMayor** [comment]
Thanks for the report! 

Fixed this same issue in the mobile app before releasing v0.0.1-alpha today, but the fix didn't make it into the webapp. 

See [this note](https://github.com/ArcadeLabsInc/arc#web-support) on discontinuing the web app for now.
