### ISSUE TITLE
A question about "A Twitter-like profile"

### ISSUE THREAD

**Issue by 0xtrr** [ArcadeLabsInc/arc#36]
Hey!

I'm hacking together a profile view but I have some questions.
1. Do we want kind 1 events in the profile view or are we kind 42 maxis?
2. Should we show followers/following counts?
3. Do we want to show follower/following count?
4. Do we want to show followers/following lists? Would show which pubkeys a users follows.

**Comment by ArcadeCityMayor** [comment]
Hi @0xtrr,

1. The current profile view shows just kind-1s. I think we'll do one tab for kind1 "posts" and kind42 "messages", not sure yet. Definitely want to support both in the ways tha tmake sense.

2/3. Yes, we will. Emulating Damus' UX now and they do. They have a separate button to 'download' followers which should be unnecessary once we get an L2 indexer like [ndxstr](https://github.com/ArcadeCity/ndxstr) up.

4. Yep we will, ditto Damus does

Happy to answer any other questions!
