### ISSUE TITLE
Bug when adding relays

### ISSUE THREAD

**Issue by leandro21b** [ArcadeLabsInc/arc#45]
I can't add new relays, every time I try to type the relay url the keyboard skips and disappears

My phone: A51

https://user-images.githubusercontent.com/107815651/216839383-4f9e4d46-aaf3-48ad-a398-047369fb0ecd.mp4

**Comment by ArcadeCityMayor** [comment]
Thanks for the report! 

We're removing manual relay management in v0.0.4 to focus on our API refactor explained [here](https://thearcapp.com/video/28).
